
# Modules
modules:
  quality_control: False
  trimming: False
  alignment_and_identification: True
  quantification: True
  DB_annotation: False
  DE_analysis: True
  coexpression: False
  visualization: False

# Filenames
samples:
  - SRR12794681
  - SRR12794682
  - SRR12794683
  - SRR12794684
  - SRR12794685
  - SRR12794686
  - SRR12794687
  - SRR12794688
  - SRR12794689
  - SRR12794690
  - SRR12794691
  - SRR12794692
  - SRR12794693
  - SRR12794694
  - SRR12794695
  - SRR12794697
  - SRR12794699
  - SRR12794700
  - SRR12794701
  - SRR12794702
  - SRR12794704
  - SRR12794705
  - SRR12794706
  - SRR12794707
  - SRR12794708
  - SRR12794709
  - SRR12794710
  - SRR12794711
  - SRR12794712
  - SRR12794714
  - SRR12794715
  - SRR12794716
  - SRR12794717
  - SRR12794718
  - SRR12794719
  - SRR12794720
  - SRR12794721
  - SRR12794722
  - SRR12794724
  - SRR12794725
  - SRR12794727
  - SRR12794728
  - SRR12794729
  - SRR12794730

# Output directory
outdir: results
# Path of reference genome files
genome_files: /media/alejandra/Elements/TFG/circrna-workflow/data/raw_data
# Genome reference GRCh37 or GRCh38 !!!
genome: GRCh38

# CONDA ENVS
envs: # By default, snakemake searchs their envs files in the same dir that rules = The path to the environment definition is interpreted as relative to the Snakefile that contains the rule
  quality_control: ../envs/quality_control.yaml  # adding '../' indicates that envs are one dir up, in the same that rules dir
  bwa: ../envs/bwa.yaml
  ciri2: ../envs/ciri2.yaml
  circexplorer2: ../envs/circexplorer2.yaml
  R: ../envs/R.yaml
  ciriquant: ../envs/ciriquant.yaml

#~~~~~~~~~~~~~~~~~~~~~~~~~~~QUALITY_CONTROL~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
quality_control:
  # Input data
  reads:
  # FASTQ file extension: "fastq.gz" or "fastq" or "fq.gz" or "fq", etc
  suffix:
    1:
    2:

  # Parameters
  threads: 6

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~TRIMMING~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
trimming:
  reads: # equal to quality_control reads. Important deixar en blanc si no s'utilitza
  suffix:
    1:
    2:

  # Parameters
  threads: 6

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ALIGNMENT_AND_IDENTIFICATION~~~~~~~~~~~~~~~~~~~~~~
aln_and_id:
  # Input data
  # Change only if trimming == "no"
  reads: /media/alejandra/Elements/TFG/circrna-workflow/results/trimming
  # Change only if trimming == "no"
  suffix:
    1: _1_val_1.fq.gz
    2: _2_val_2.fq.gz
  bwa_index: # poner prefix.
  reference: # NOT COMPRESSED FILES
  annotation:
  refFlat:

  # Parameters
  sample_threshold: 2 # Minimum number of circRNA reads in one sample to be included.
  merged_threshold: 2 # Minimum number of circRNA reads in total to be included.
  threads:
    bwa: 3    # Alignment tool
    ciri2: 3  # Identification tool
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~QUANTIFICATION~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
quantification:
  # Input data
  # Change only if trimming == "no"
  reads: /media/alejandra/Elements/TFG/circrna-workflow/results/trimming
  # Change only if trimming == "no"
  read_suffix:
    1: _1_val_1.fq.gz
    2: _2_val_2.fq.gz
  circRNAs:
  circ_suffix:

  reference:
  annotation:
  bwa_index:
  hisat2_index:
  fai_index:
  # localted in the same dir that ref
  # Parameters
  sample_threshold: 2 # Minimum number of circRNA reads in one sample to be included.
  merged_threshold: 2 # Minimum number of circRNA reads in total to be included.
  # 0: unstranded, 1: read1 match the sense strand, 2: read1 match the antisense strand
  library_type: 1
  threads:
    ciriquant: 6
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ANNOTATION~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
annotation:
  # Input data
  file:
  # Parameters
  # Extra fields: genomic.length, spliced.seq, length, samples, repeats, annotation, best.transcript, gene.symbol, circRNA.study
  fields: genomic.length repeats annotation gene.symbol  # sin commas. Poner así

#~~~~~~~~~~~~~~~~~~DIFFERENTIAL_EXPRESSION_ANALYSIS~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Complete only if quantification == 'yes'
DE:
  # Input data
  metadata: /media/alejandra/Elements/TFG/circrna-workflow/data/metadata/metadata.csv # Sample, Group, (Sex) variable columns

  # Parameters
  metadata_sep: comma
  design: ~group+sex
  pvalue: 0.05
  fold_change: 2

#~~~~~~~~~~~~~~~~~~~~~~~~~COEXPRESSION~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
netminer:
  # Input data
  count_data:
  metadata:
  gene_length:

  # Parameters
  metadata_sep:
  design: ~group
  threads: 5 # minimun
  percThreshold: 0.005
  S1N: 3
  S2N: 2

#~~~~~~~~~~~~~~~~~~~~~~~~~~QC_VISUALIZATION~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
visualization:
  # Input data
  # 1st column = rownames. 1st row = colnames
  count_data:
  metadata:

  # Parameters
  normalized: False
  metadata_sep: comma
  design:

  # Image settings
  # device: pdf, jpeg, pgn or svg
  out_format: svg
  units: in
  width: 12
  height: 12
