samples:
  - SRR12794696
  - SRR12794698
  - SRR12794703
  - SRR12794710
  - SRR12794713
  - SRR12794716
  - SRR12794723
  - SRR12794726

path:
  raw_reads: data/raw_data/samples
  trimmed_reads: data/trimmed_data
  genome_files: data/raw_data


genome:
  - GRCh38

suffix:
  raw:
    1: _1.fastq.gz
    2: _2.fastq.gz
  trimmed:
    1: _1_val_1.fq.gz
    2: _2_val_2.fq.gz

threads:
  fastqc: 3
  bwa: 3
  ciri2: 1
  ciriquant: 5

envs:
  quality_control:
  bwa: envs/bwa.yaml
  ciri2: envs/ciri2.yaml
  circexplorer2: envs/circexplorer2.yaml
  R: envs/R.yaml
