
# Modules
modules:
  quality_control: no
  trimming: no
  alignment_and_identification: no
  quantification: no
  DE_analysis: no
  visualization: yes

# Filenames
samples:
  - SRR12794685
  - SRR12794695
  - SRR12794703
  - SRR12794706
  - SRR12794713
  - SRR12794715
  - SRR12794724
  - SRR12794728

# Output directory
outdir: lib
# Path of reference genome files
genome_files: data/raw_data
# Genome reference GRCh37 or GRCh38 !!!
genome: GRCh38

# CONDA ENVS
envs: # By default, snakemake searchs their envs files in the same dir that rules = The path to the environment definition is interpreted as relative to the Snakefile that contains the rule
  quality_control: ../envs/quality_control.yaml  # adding '../' indicates that envs are one dir up, in the same that rules dir
  bwa: ../envs/bwa.yaml
  ciri2: ../envs/ciri2.yaml
  circexplorer2: ../envs/circexplorer2.yaml
  R: ../envs/R.yaml
  ciriquant: ../envs/ciriquant.yaml

#~~~~~~~~~~~~~~~~~~~~~~~~~~~QUALITY_CONTROL~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
quality_control:
  reads: data/raw_data/samples
  # FASTQ file extension: "fastq.gz" or "fastq" or "fq.gz" or "fq", etc
  suffix:
    1: _1.fastq.gz
    2: _2.fastq.gz
  fastqc_threads: 3

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~TRIMMING~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
trimming:
  reads: data/raw_data/samples # equal to quality_control reads. Important deixar en blanc si no s'utilitza
  suffix:
    1: _1.fastq.gz
    2: _2.fastq.gz
  fastqc_threads: 3

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ALIGNMENT_AND_IDENTIFICATION~~~~~~~~~~~~~~~~~~~~~~
aln_&_id:
  # Change only if trimming == "no"
  reads: test/data/trimmed
  # Change only if trimming == "no"
  suffix:
    1: _1_val_1.fq.gz
    2: _2_val_2.fq.gz
  threads:
    bwa: 3    # Alignment tool
    ciri2: 3  # Identification tool

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~QUANTIFICATION~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
quantification:
  # Change only if trimming == "no"
  reads: test/data/trimmed
  # Change only if trimming == "no"
  suffix:
    1: _1_val_1.fq.gz
    2: _2_val_2.fq.gz
  threads:
    ciriquant: 5

#~~~~~~~~~~~~~~~~~~DIFFERENTIAL_EXPRESSION_ANALYSIS~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
prep_DE: # only if quantification == 'yes'
  group:
    - Multiple sclerosis
    - Multiple sclerosis
    - Multiple sclerosis
    - Multiple sclerosis
    - Healthy control
    - Healthy control
    - Healthy control
    - Healthy control
  sex:
    - female
    - female
    - male
    - male
    - male
    - male
    - female
    - female

DE:
  design: ~group+sex
  pvalue:
  fold_change:

#~~~~~~~~~~~~~~~~~~~~~~~~~COEXPRESSION~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
netminer:
  filepath:
  threads:
  percThreshold: 0.005
  S1N: 3
  S2N: 2

#~~~~~~~~~~~~~~~~~~~~~~~~~~VISUALIZATION~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
visualization:
  count_data: libs/DE_analysis/circular_counts_sub.csv
  metadata: libs/DE_analysis/circular_info.csv
  normalized: no
  out_format: pdf
