##############################~GENERAL_CONFIGURATION~###########################

# 1. MODULE EXECUTION (True or False). Select the workflow module to execute.

modules:
  quality_control: False
  trimming: False
  alignment_and_identification: False
  quantification: False
  DB_annotation: False
  DE_analysis: False
  visualization: False

# 2. FILENAMES. Specify the name of your files

samples:
- Sample1
- Sample2

# 3. OUTPUT DIRECTORY. Specify the absolute path of your output directory.

outdir: 

# 4. GENOME REFERENCE FILES. Required for alignment and quantification modules. You can select your own specific files, specifying the absolute path of the directory containing the index, reference and annotation genome files. Alternatively, if you prefer, those files are automatically downloaded for you. In this case, specify an existent or future directory that will contain those files.

genome_files:

# 5. GENOME REFERENCE VERSION (GRCh37 or GRCh38). Specify the version of your reference genome files. GRCh37 version is under testing.

genome: GRCh38

# 6. CONDA ENVIRONMENTS. For the automatically handle of depedencies, do not change these paths. Alternatively, user can specify their own paths.

envs: # By default, snakemake searchs their envs files in the same directory that rules. Then, the path to the environment definition is interpreted as relative to the Snakefile that contains the rule
  quality_control: ../envs/quality_control.yaml  # adding '../' indicates that envs are one dir up, in the same that rules dir
  bwa: ../envs/bwa.yaml
  ciri2: ../envs/ciri2.yaml
  circexplorer2: ../envs/circexplorer2.yaml
  R: ../envs/R.yaml
  ciriquant: ../envs/ciriquant.yaml

######################~MODULE_SPECIFIC_CONFIGURATION~###########################
# Complete only the specific configuration of module selected to execute.

#~~~~~~~~~~~~~~~~~~~~~~~~~~~QUALITY_CONTROL~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
quality_control:
  # Input Data
  reads:
  # FASTQ file extension: "fastq.gz" or "fastq" or "fq.gz" or "fq", etc
  suffix:
    1:
    2:

  # Parameters
  threads:

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~TRIMMING~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
trimming:
  # Input Data
  reads:            # equal to quality_control reads
  suffix:
    1:
    2:

  # Parameters
  threads:

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ALIGNMENT_AND_IDENTIFICATION~~~~~~~~~~~~~~~~~~~~~~
aln_and_id:
  # Input Data
  reads:
  suffix:
    1:
    2:
  bwa_index:        # Prefix
  reference:        # NOT COMPRESSED FILES
  annotation:
  refFlat:

  # Parameters
  sample_threshold: 2 # Minimum number of circRNA reads in one sample to be included.
  merged_threshold: 2 # Minimum number of circRNA reads in total to be included.
  threads:
    bwa:                # Alignment tool
    ciri2:              # Identification tool
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~QUANTIFICATION~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
quantification:
  # Input Data
  reads:
  read_suffix:
    1: _1_val_1.fq.gz
    2: _2_val_2.fq.gz
  circRNAs: 
  circ_suffix: _common.txt
  
  # Annotation and Index Files
  reference:
  annotation:
  bwa_index:
  hisat2_index:
  fai_index:          # localted in the same dir that reference file
  
  # Parameters
  sample_threshold: 2 # Minimum number of circRNA reads in one sample to be included.
  merged_threshold: 2 # Minimum number of circRNA reads in total to be included.
  # 0: unstranded, 1: read1 match the sense strand, 2: read1 match the antisense strand
  library_type: 2
  threads:
    ciriquant:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ANNOTATION~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
annotation:
  # Input data
  file: 
  # Parameters
  # Extra Fields: genomic.length, spliced.seq, length, samples, repeats, annotation, best.transcript, gene.symbol, circRNA.study
  fields: genomic.length repeats annotation gene.symbol

#~~~~~~~~~~~~~~~~~~DIFFERENTIAL_EXPRESSION_ANALYSIS~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DE:
  # Input Data
metadata: 

  # Parameters
  metadata_sep: comma   # comma, semicolon, tab, whitespace
  design: ~group+sex
  pvalue: 0.05
  fold_change: 2

#~~~~~~~~~~~~~~~~~~~~~~~~~~QC_VISUALIZATION~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
visualization:
  # Input Data
  count_data:           # 1st column = rownames. 1st row = colnames
  metadata:             # Sample, Group and (Sex) variable columns

  # Parameters
  normalized:            # True or False
  metadata_sep:          # comma, semicolon, tab, whitespace
  design: ~group+sex

  # Image Dettings
  out_format: svg       # pdf, jpeg, pgn or svg
  units: in             # inches(in) or centimetres (cm)
  width: 12
  height: 12
